#!/usr/bin/perl

use strict;
use warnings;

use lib 'lib';

use Insteon::PLM;

my $plm = Insteon::PLM->new('/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A60334HH-if00-port0');

my $command = shift;

# Beep everything?
#$plm->send_insteon_group(9, '30');

my $cb = sub {
    print join(", ", @_) . "\n";
};

$plm->$command(@ARGV, $cb);

$plm->loop();
