#!/usr/bin/perl

use strict;
use warnings;

use lib 'lib';

use Insteon::PLM;

my $plm = Insteon::PLM->new('/dev/ttyUSB0');

# Beep everything?
$plm->send_insteon_group(9, '30');

my $cb = sub {
    print @_;
};

#$plm->get_im_aldb($cb);

$plm->loop();
